name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - v2.3.x
          - v2.4.x
          - v2.5.x
          - v2.6.x
        gemfile:
          - gemfiles/rails_4_0.gemfile
          - gemfiles/rails_4_1.gemfile
          - gemfiles/rails_4_2.gemfile
          - gemfiles/rails_5_0.gemfile
          - gemfiles/rails_5_1.gemfile
          - gemfiles/rails_5_2.gemfile
          - gemfiles/rails_6_0.gemfile
        exclude:
          # Rails 6.0 requires Ruby 2.5+
          - ruby:    v2.3.x
            gemfile: gemfiles/rails_6_0.gemfile
          - ruby:    v2.4.x
            gemfile: gemfiles/rails_6_0.gemfile

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependency
        run: |
          set -xe
          sudo apt-get update
          sudo apt-get install libsqlite3-dev -y

      - name: Setup rubygems and bundler
        run: |
          set -xe
          gem update --system
          gem install bundler --no-document -v 1.17.3 || true

      - name: bundle install
        run: |
          set -xe
          bundle install --jobs 4 --retry 3
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}

      - name: setup cc-test-reporter
        run: |
          set -xe
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: run test
        run: |
          set -xe
          bundle exec rspec
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
          CI: "true"

      - name: run test (with MJIT)
        run: |
          set -xe

          if [[ "${{ matrix.ruby }}" > "v2.6." ]]; then
            RUBYOPT=--jit bundle exec rspec
          fi
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
          CI: "true"

      - name: teardown cc-test-reporter
        run: |
          ./cc-test-reporter after-build --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
